/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ProjectLogRouteImport } from './routes/project-log'
import { Route as MissionProgressRouteImport } from './routes/mission-progress'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResearchSlugRouteImport } from './routes/research.$slug'
import { Route as ProjectLogSlugRouteImport } from './routes/project-log.$slug'

const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectLogRoute = ProjectLogRouteImport.update({
  id: '/project-log',
  path: '/project-log',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionProgressRoute = MissionProgressRouteImport.update({
  id: '/mission-progress',
  path: '/mission-progress',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchSlugRoute = ResearchSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ResearchRoute,
} as any)
const ProjectLogSlugRoute = ProjectLogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjectLogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mission-progress': typeof MissionProgressRoute
  '/project-log': typeof ProjectLogRouteWithChildren
  '/research': typeof ResearchRouteWithChildren
  '/project-log/$slug': typeof ProjectLogSlugRoute
  '/research/$slug': typeof ResearchSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mission-progress': typeof MissionProgressRoute
  '/project-log': typeof ProjectLogRouteWithChildren
  '/research': typeof ResearchRouteWithChildren
  '/project-log/$slug': typeof ProjectLogSlugRoute
  '/research/$slug': typeof ResearchSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mission-progress': typeof MissionProgressRoute
  '/project-log': typeof ProjectLogRouteWithChildren
  '/research': typeof ResearchRouteWithChildren
  '/project-log/$slug': typeof ProjectLogSlugRoute
  '/research/$slug': typeof ResearchSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mission-progress'
    | '/project-log'
    | '/research'
    | '/project-log/$slug'
    | '/research/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mission-progress'
    | '/project-log'
    | '/research'
    | '/project-log/$slug'
    | '/research/$slug'
  id:
    | '__root__'
    | '/'
    | '/mission-progress'
    | '/project-log'
    | '/research'
    | '/project-log/$slug'
    | '/research/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MissionProgressRoute: typeof MissionProgressRoute
  ProjectLogRoute: typeof ProjectLogRouteWithChildren
  ResearchRoute: typeof ResearchRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-log': {
      id: '/project-log'
      path: '/project-log'
      fullPath: '/project-log'
      preLoaderRoute: typeof ProjectLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission-progress': {
      id: '/mission-progress'
      path: '/mission-progress'
      fullPath: '/mission-progress'
      preLoaderRoute: typeof MissionProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/$slug': {
      id: '/research/$slug'
      path: '/$slug'
      fullPath: '/research/$slug'
      preLoaderRoute: typeof ResearchSlugRouteImport
      parentRoute: typeof ResearchRoute
    }
    '/project-log/$slug': {
      id: '/project-log/$slug'
      path: '/$slug'
      fullPath: '/project-log/$slug'
      preLoaderRoute: typeof ProjectLogSlugRouteImport
      parentRoute: typeof ProjectLogRoute
    }
  }
}

interface ProjectLogRouteChildren {
  ProjectLogSlugRoute: typeof ProjectLogSlugRoute
}

const ProjectLogRouteChildren: ProjectLogRouteChildren = {
  ProjectLogSlugRoute: ProjectLogSlugRoute,
}

const ProjectLogRouteWithChildren = ProjectLogRoute._addFileChildren(
  ProjectLogRouteChildren,
)

interface ResearchRouteChildren {
  ResearchSlugRoute: typeof ResearchSlugRoute
}

const ResearchRouteChildren: ResearchRouteChildren = {
  ResearchSlugRoute: ResearchSlugRoute,
}

const ResearchRouteWithChildren = ResearchRoute._addFileChildren(
  ResearchRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MissionProgressRoute: MissionProgressRoute,
  ProjectLogRoute: ProjectLogRouteWithChildren,
  ResearchRoute: ResearchRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
